name: multichannel_flutter_sample
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.2.1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  qiscus_multichannel_widget:
    path: ../
  grouped_list: ^5.1.1
  date_format: ^2.0.5
  url_launcher: ^6.1.7
  go_router: ^6.0.7
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# dependency_overrides:
#   qiscus_chat_sdk:
#     path: ../../qiscus-chat-sdk-flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
